# Generated by Django 5.1 on 2025-04-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id_edificio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('tipo', models.TextField(max_length=255)),
                ('saturado', models.TextField(max_length=255)),
                ('fac', models.TextField(max_length=255)),
            ],
        ),
    ]
